# Name of the workflow (shows up in GitHub Actions UI)
name: E-Commerce Model CI/CD

# Define when this workflow should run
on:
  # Trigger workflow on push to "develop" branch
  push:
    branches: [ "develop" ]
  # Trigger workflow when a pull request targets "develop" branch
  pull_request:
    branches: [ "develop" ]
  # Allow running workflow manually from the GitHub Actions tab
  workflow_dispatch:

# Define the jobs in the workflow
jobs:
  # ------------------------
  # 1. BUILD JOB
  # ------------------------
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Checkout repository
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # ------------------------
  # 2. TEST JOB
  # ------------------------
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: pytest tests/
      - name: Run Jupyter Notebook end-to-end
        run: |
          pip install nbconvert papermill
          papermill notebooks/model.ipynb notebooks/output.ipynb

  # ------------------------
  # 3. DEPLOY JOB
  # ------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Save trained model
        run: |
          mkdir -p artifacts
          python scripts/train_and_save.py  # Exports model.pkl
          cp notebooks/output.ipynb artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ecommerce-model
          path: artifacts/
